Этап 1. Сервис статистики
alekseybch/java-explore-with-me pull request #2
Opened 2023-01-28 23:35 UTC by alekseybch

2023-01-30 23:49 UTC, NikolaiDem requested changes

2023-01-30 23:49 UTC, NikolaiDem commented on stats/src/main/java/ru/practicum/ewm/service/StatsService.java
> +    List<ResponseStatsDto> findStats(LocalDateTime startDate, LocalDateTime endDate, String[] urisSplit, Boolean unique);
Здесь тоже аргументы лучше собрать в dto.

2023-01-30 23:49 UTC, NikolaiDem commented on stats/src/main/resources/schema.sql
> +    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
Для однозначности лучше не обозначать поля служебными словами timestamp.

2023-01-30 23:49 UTC, NikolaiDem commented on stats/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS hits
Еще лучше сделать таблицу с приложениями, где будет его id и название.
Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу hits.

2023-01-31 14:14 UTC, alekseybch commented
1. Изменена архитектура, клиент и дто перенесены в модуль статистики и подключаются зависимостями
2. Добавлен общий дто параметров
3. Имя программы задается в application.properties
4. В schema.sql поправлено имя столбца timestamp и добавлена новая таблица apps

2023-02-15 13:26 UTC, merged